### ISSUE TITLE
`NoneType` errors with ST4068

### ISSUE THREAD

**Issue by jrappen** [braver/SideBarTools#30]
Lately SideBarTools has been running into the following issues:

```text
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1172, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/xxx/Library/Application Support/Sublime Text/Installed Packages/SideBarTools.sublime-package/SideBar.py", line 78, in is_visible
AttributeError: 'NoneType' object has no attribute 'file_name'
```

and

```text
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 1172, in is_visible_
    ret = self.is_visible(**args)
  File "/Users/xxx/Library/Application Support/Sublime Text/Installed Packages/SideBarTools.sublime-package/SideBar.py", line 40, in is_visible
AttributeError: 'NoneType' object has no attribute 'file_name'
```

---

```yaml
Sublime Text:
  build: 4068
  channel: dev
    portable: false
  platform: osx x64

System:
  hardware: MBP 15" 2018, i9 2.9GHz, 32GB, 1TB, Radeon Pro 560X
  software: macOS Catalina 10.15.4 (19E266)
    open_gl:
      gl_api_version: 4.1 INTEL-14.5.22
      glsl_version: 4.10
      vendor: Intel Inc.
      renderer: Intel(R) UHD Graphics 630
```

**Comment by braver** [comment]
I'm on a similar setup, but don't see that error. Is this when running a particular command? 

It seems to point to a case where `self.window.active_view()` is None, which to me seems kinda weird. There is always a window and windows always have an active_view.. right?

**Comment by jrappen** [comment]
Closing as stale.
